version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx  
    restart: always
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - app

  app:    
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: "node index.js"
    tty: true
    build:
      context: ./node  
    volumes:      
      - ./node:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - node-network
    depends_on:
      - db
  db:
    image: mysql:5.7    
    container_name: db
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb     
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
    